services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks: [fcnet]
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_DATABASE: "fixchain"
      FIXER_RAG_COLLECTION: "fixer_rag_collection"
      SCANNER_RAG_COLLECTION: "scanner_rag_collection"
      LOG_LEVEL: "INFO"
      SERENA_ENABLED: "true"
      SERENA_TIMEOUT_S: "45"
    volumes:
      - ./.mcp.json:/app/.mcp.json
    depends_on:
      - mongodb
    restart: unless-stopped
    networks: [fcnet]

volumes:
  mongo_data:
  
networks:
  fcnet:
    driver: bridge