services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MONGODB_URI: "mongodb://mongodb:27017/"
      MONGODB_DATABASE: "fixchain"
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
